"""remove_positional_columns

Revision ID: 0896862964bf
Revises: e84c6de05179
Create Date: 2026-06-24 10:49:00.930230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0896862964bf'
down_revision: Union[str, Sequence[str], None] = 'e84c6de05179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'width')
    op.drop_column('nodes', 'offset_y')
    op.drop_column('nodes', 'height')
    op.drop_column('nodes', 'offset_x')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('offset_x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('offset_y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
