"""remove_node_color

Revision ID: 7534d6f119ba
Revises: 4d691f7a1d67
Create Date: 2026-06-30 10:16:50.572318

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7534d6f119ba"
down_revision: str | Sequence[str] | None = "4d691f7a1d67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "color")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("color", sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
