"""add_graph_history

Revision ID: 8e0d2a8af248
Revises: 127baf24a53c
Create Date: 2026-07-19 11:38:42.107439

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e0d2a8af248'
down_revision: str | Sequence[str] | None = '127baf24a53c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('flow_json', sa.JSON(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('graphs', sa.Column('current_history_sequence', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphs', 'current_history_sequence')
    op.drop_table('graph_history')
    # ### end Alembic commands ###
