"""add_expression_type

Revision ID: ba83352ad817
Revises: 0896862964bf
Create Date: 2026-06-24 13:35:38.572376

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba83352ad817"
down_revision: str | Sequence[str] | None = "0896862964bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expressions", sa.Column("type", sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expressions", "type")
    # ### end Alembic commands ###
