"""add_to_expression_id_to_edge

Revision ID: cfebe1f0cace
Revises: ba83352ad817
Create Date: 2026-06-28 15:53:27.341207

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfebe1f0cace"
down_revision: str | Sequence[str] | None = "ba83352ad817"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("edges", sa.Column("to_expression_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "edges", "expressions", ["to_expression_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "edges", type_="foreignkey")
    op.drop_column("edges", "to_expression_id")
    # ### end Alembic commands ###
